### ISSUE TITLE
I can't run that on my server

### ISSUE THREAD

**Issue by RzeszowPL** [TryHardHusky/cardbot#1]
I have a lot of errors
```
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'doctormckay/steam-crypto' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'steam-client'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.4.11-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "steam-client"
npm ERR! cwd /home/pi/Documents/cardbot-master
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Documents/cardbot-master/npm-debug.log
npm ERR! not ok code 0

```
Can you tell me how to set this up?

**Comment by TryHardHusky** [comment]
Run `nmp installl`    
https://github.com/TryHardHusky/cardbot#setup

**Comment by RzeszowPL** [comment]
i have npm installed

**Comment by TryHardHusky** [comment]
1) Copy the files into desired location
2) open command prompt
3) Use `cmd` to navigate to the directory containing the bot
EG: `cd C:\Users\Kain\projects\cardbot\`  
4) Type `npm install` and press enter.  
5) This will create the `node_modules` directory.  After that you can run the `bot.js` or `auth.js`

**Comment by RzeszowPL** [comment]
i can't do this 
![image](https://cloud.githubusercontent.com/assets/6783135/18912196/7ee30496-8581-11e6-81aa-4e99e7baf40b.png)

**Comment by TryHardHusky** [comment]
Try installing steam-crypto.  
`npm install steam-crypto --save`

**Comment by RzeszowPL** [comment]
How to configure that i run auth.js and what is this Steam id ?
